version: '3'
services:
  proxy:
    image: 'redis:${REDIS_TAG}'
    networks:
      - frontend
  app:
    image: repo/app
    networks:
      - frontend
      - backend
  db:
    image: redis
    networks:
      backend:
        aliases:
        - database
networks:
  frontend:
  backend:
    external: true

